### ISSUE TITLE
Error bad decrypt when using  openssl enc 

### ISSUE THREAD

**Issue by mkulshershtha** [forcedotcom/sfdx-bitbucket-org#8]
**PS C:\openssl\OpenSSL-Win64\bin>** openssl enc -nosalt -aes-256-cbc -in server.key -out server.key.enc -md sha1  -K 

**output**: AEB27AF52BC605687840C6CA7A4321E1076E994D8DE706C680A403E09478DE8E  -iv CBDCC2C817A6087D43CD404804DF896C

**PS C:\openssl\OpenSSL-Win64\bin>** openssl enc -nosalt -aes-256-cbc -d -in server.key.enc -out server.key -base64 -K AEB27AF52BC605687840C6CA7A4321E1076E994D8DE706C680A403E09478DE8E -iv CBDCC2C817A6087D43CD404804DF896C
bad decrypt
88400000:error:1C80006B:Provider routines:ossl_cipher_generic_block_final:wrong final block length:providers\implementations\ciphers\ciphercommon.c:429:

**Comment by muneeb-fullskope** [comment]
how to resolve this error? I am also getting 4077795DD97F0000:error:1C80006B:Provider routines:ossl_cipher_generic_block_final:wrong final block length:../providers/implementations/ciphers/ciphercommon.c:429:
